### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by feiss** [ten-lang/ten-lang#1]
In the "Hello Person" sample, where it says:

`"What's you're name? "`

it should say:

`"What's your name? "`

**Comment by raystubbs** [comment]
Hah, thanks.  Fkn English ;)

**Comment by raystubbs** [comment]
Hey @feiss , I kinda' screwed up my hand; so won't be typing much in the next few days.  If I give you commit privilege would you be willing to fix this and any other typo's you find in this repo and [`libten/docs`](https://github.com/ten-lang/libten/docs]?  Just anything you notice would be great, no need to go looking for issues if that'd be too much effort.  Would really appreciate it!
